sudo: required
services:
 - docker

before_install:
  - docker build -t zhousidun82/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true zhousidun82/docker-react npm run test -- --coverage
 