sudo: required
services:
 - docker

before_install:
  - docker build -t zhousidun82/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true zhousidun82/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-838291631450"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY